version: '3.2'
services:
  binancesloth:
    build:
      dockerfile: "Dockerfile"
      context: .
    container_name: "binancesloth"
    volumes:
      - type: bind
        source: ./
        target: /app/binancesloth
    working_dir: /app/binancesloth
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["python3", "main-v1.py", "-c", "/app/binancesloth/config/config.Aom.json"]